/*
 * TIMER2_config.h
 *
 *  Created on: Jul 30, 2022
 *      Author: abano
 */

#ifndef MCAL_TIMER2_TIMER2_CONFIG_H_
#define MCAL_TIMER2_TIMER2_CONFIG_H_

/*
TIM2_NormalWAVEmood
TIM2_PHASEcorrectWAVmood
TIM2_CTCMood
TIM2_FastPWM				 */

#define WAVEG_MOOD			TIM2_NormalWAVEmood
/*TIM2_OC2NC
TIM2_ToggleOC2
TIM2_CleraONCOMMATCH
TIM2_SETONCOMMATCH	*/

#define OC2_OUTMOOD			TIM2_OC2NC
/*TIM2_PRE1
TIM2_PRE8
TIM2_PRE32
TIM2_PRE64
TIM2_PRE128
TIM2_PRE256
TIM2_PRE1024*/

#define PRESCALLER			TIM2_PRE1024

/*
COMPMATCH_INTER
OVERFLOW_INTER
NON						*/
#define INTERRUPT_MOOD		OVERFLOW_INTER
#endif /* MCAL_TIMER2_TIMER2_CONFIG_H_ */
